export const SkillsList = [
  { id: 1, name: "HTML", image: "/assets/images/skills-images/html5.svg" },
  { id: 2, name: "CSS", image: "/assets/images/skills-images/css.svg" },
  {
    id: 3,
    name: "JavaScript",
    image: "/assets/images/skills-images/javascript.svg",
  },
  {
    id: 4,
    name: "TypeScript",
    image: "/assets/images/skills-images/typescript.svg",
  },
  {
    id: 488,
    name: "C#",
    image: "/assets/images/skills-images/csharp.svg",
  },
  {
    id: 5,
    name: "Tailwind CSS",
    image: "/assets/images/skills-images/tailwindcss.svg",
  },
  { id: 6, name: "React.js", image: "/assets/images/skills-images/react.svg" },
  {
    id: 7,
    name: "React Native",
    image: "/assets/images/skills-images/react-native-1.svg",
  },
  {
    id: 8,
    name: "Next.js",
    image: "/assets/images/skills-images/nextjs_icon_dark.svg",
  },
  { id: 9, name: "Expo", image: "/assets/images/skills-images/expo.svg" },
  { id: 10, name: "Node.js", image: "/assets/images/skills-images/nodejs.svg" },
  {
    id: 11,
    name: "Express.js",
    image: "/assets/images/skills-images/Express.js_light.svg",
  },
  {
    id: 111,
    name: "Asp .net core",
    image: "/assets/images/skills-images/asp.net-core.webp",
  },
  { id: 12, name: "Git", image: "/assets/images/skills-images/git.svg" },
  { id: 13, name: "GitHub", image: "/assets/images/skills-images/github.svg" },
  { id: 14, name: "docker", image: "/assets/images/skills-images/docker.svg" },
  {
    id: 15,
    name: "Firebase",
    image: "/assets/images/skills-images/firebase.svg",
  },
  {
    id: 16,
    name: "MongoDB",
    image: "/assets/images/skills-images/mongodb-icon-2.svg",
  },
  {
    id: 17,
    name: "Supabase",
    image: "/assets/images/skills-images/supabase.svg",
  },
  {
    id: 18,
    name: "mongoose",
    image: "/assets/images/skills-images/mongoose-1.svg",
  },
  {
    id: 180,
    name: "Entity Framework",
    image: "/assets/images/skills-images/entity-framework.webp",
  },
  {
    id: 19,
    name: "NextAuth",
    image: "/assets/images/skills-images/next-auth.svg",
  },
  { id: 20, name: "Auth0", image: "/assets/images/skills-images/auth0.svg" },
  { id: 21, name: "Clerk", image: "/assets/images/skills-images/clerk.webp" },
  { id: 22, name: "Kinde", image: "/assets/images/skills-images/kinde.webp" },
  {
    id: 23,
    name: "Postman",
    image: "/assets/images/skills-images/postman(1).svg",
  },
  {
    id: 24,
    name: "Thunder Client",
    image: "/assets/images/skills-images/thunder-client.svg",
  },
  {
    id: 25,
    name: "swagger",
    image: "/assets/images/skills-images/swagger.svg",
  },
  { id: 26, name: "Figma", image: "/assets/images/skills-images/figma.svg" },
  { id: 260, name: "VsCode", image: "/assets/images/skills-images/vscode.svg" },
  {
    id: 265,
    name: "Visual Studio",
    image: "/assets/images/skills-images/visual-studio.svg",
  },
  {
    id: 266,
    name: "Cursor",
    image: "/assets/images/skills-images/cursor.webp",
  },
  {
    id: 267,
    name: "Windsurf",
    image: "/assets/images/skills-images/windsurf.webp",
  },
  {
    id: 267,
    name: "Android Studio",
    image: "/assets/images/skills-images/Android_Studio.webp",
  },
  {
    id: 27,
    name: "Shadcn UI",
    image: "/assets/images/skills-images/shadcn.webp",
  },
  {
    id: 28,
    name: "Material Tailwind",
    image: "/assets/images/skills-images/logo-mt.svg",
  },
  {
    id: 29,
    name: "Daisy UI",
    image: "/assets/images/skills-images/daisy-ui.svg",
  },
  {
    id: 30,
    name: "Aceternity UI",
    image: "/assets/images/skills-images/aceternity-ui.svg",
  },
  {
    id: 31,
    name: "Chakra UI",
    image: "/assets/images/skills-images/chakra-ui.svg",
  },
  { id: 32, name: "npm", image: "/assets/images/skills-images/npm.webp" },
  { id: 32, name: "Bun", image: "/assets/images/skills-images/bun.svg" },
  { id: 33, name: "Zod", image: "/assets/images/skills-images/zod.svg" },
  {
    id: 34,
    name: "React Hook Form",
    image: "/assets/images/skills-images/react-hook-form-logo-only.svg",
  },
  { id: 35, name: "axios", image: "/assets/images/skills-images/axios.svg" },
  { id: 36, name: "SWR", image: "/assets/images/skills-images/SWR_light.svg" },
  { id: 37, name: "bcryptjs" },
  { id: 38, name: "jwt", image: "/assets/images/skills-images/jwt.svg" },
  { id: 39, name: "helmet.js" },
  { id: 40, name: "SEO", image: "/assets/images/skills-images/seo.svg" },
  {
    id: 41,
    name: "next-intl",
    image: "/assets/images/skills-images/next-intl.svg",
  },
  {
    id: 42,
    name: "socket.io",
    image: "/assets/images/skills-images/socket-io.svg",
  },
  {
    id: 43,
    name: "REST API",
    image: "/assets/images/skills-images/api-svgrepo-com.svg",
  },
  {
    id: 44,
    name: "Redux Toolkit",
    image: "/assets/images/skills-images/redux.svg",
  },
  { id: 45, name: "Redux Persist" },
  {
    id: 46,
    name: "Expo router",
    image: "/assets/images/skills-images/expo-router.webp",
  },
  {
    id: 47,
    name: "NativeWind",
    image: "/assets/images/skills-images/NativeWind.webp",
  },
  {
    id: 48,
    name: "Problem Solving",
    image: "/assets/images/skills-images/mind-smart-light-bulb-svgrepo-com.svg",
  },
  {
    id: 49,
    name: "Framer Motion",
    image: "/assets/images/skills-images/Framer_light.svg",
  },
  {
    id: 59,
    name: "Reanimated",
    image: "/assets/images/skills-images/Reanimated.webp",
  },
  { id: 50, name: "clsx" },
  { id: 52, name: "tailwind merge" },
  { id: 51, name: "next-seo" },
  { id: 53, name: "next-themes" },
  {
    id: 54,
    name: "lenis scroll",
    image: "/assets/images/skills-images/lenis-new-smooth-scroll-library.svg",
  },
  {
    id: 55,
    name: "react-hot-toast",
    image: "/assets/images/skills-images/react-hot-toast.webp",
  },
  {
    id: 60,
    name: "react-toastify",
  },
  { id: 56, name: "sonner", image: "/assets/images/skills-images/sonner.webp" },
  {
    id: 57,
    name: "resend",
    image: "/assets/images/skills-images/resend-wordmark-black.svg",
  },
  {
    id: 57,
    name: "next.js-toploader",
    image: "/assets/images/skills-images/next.js-toploader.webp",
  },
  { id: 58, name: "react-native-responsive-screen" },
  { id: 580, name: "recharts" },
  { id: 583, name: "MongoDB Driver" },
];
